    'A'   => { 'S' => 'MORA - Grid MORA' },
      'D' => {
        ''  => 'Navaid - VHF Navaid',
        'B' => 'Navaid - NDB Navaid',
      },
      'E' => {
        'A' => 'Enroute - Grid Waypoints',
        'M' => 'Enroute - Airway Markers',
        'P' => 'Enroute - Holding Patterns',
        'R' => 'Enroute - Airways and Routes',
        'T' => 'Enroute - Preferred Routes',
        'U' => 'Enroute - Airway Restrictions',
        'V' => 'Enroute - Airway Restrictions',
      },
      'H' => {
        'A' => 'Heliport - Pads',
        'C' => 'Heliport - Terminal Waypoints',
        'D' => 'Heliport - SIDs',
        'E' => 'Heliport - STARs',
        'F' => 'Heliport - Approach Procedures',
        'K' => 'Heliport - TAA',
        'S' => 'Heliport - MSA',
        'V' => 'Heliport - Communications',
      },
      'P' => {
        'A' => 'Airport - Reference Points',
        'B' => 'Airport - Gates',
        'C' => 'Airport - Terminal Waypoints',
        'D' => 'Airport - SIDs',
        'E' => 'Airport - STARs',
        'F' => 'Airport - Approach Procedures',
        'G' => 'Airport - Runways',
        'I' => 'Airport - Localizer/Glide Slope',
        'K' => 'Airport - TAA',
        'L' => 'Airport - MLS',
        'M' => 'Airport - Localizer Marker',
        'N' => 'Airport - Terminal NDB',
        'P' => 'Airport - Path Point',
        'R' => 'Airport - Flt Planning ARR/DEP',
        'S' => 'Airport - MSA',
        'T' => 'Airport - GLS Station',
        'V' => 'Airport - Communications',
      },
      'R' => {
        ''  => 'Company Routes - Company Routes',
        'A' => 'Company Routes - Alternate Records',

      },
      'T' => {
        'C' => 'Tables - Cruising Tables',
        'G' => 'Tables - Geographical Reference',
        'N' => 'Tables - RNAV Name Table',
      },
      'U' => {
        'C' => 'Airspace - Controlled Airspace',
        'F' => 'Airspace - FIR/UIR',
        'R' => 'Airspace - Restrictive Airspace',
      }
